# Generated by Django 5.2.3 on 2025-06-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0003_alter_review_created_at_alter_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model': ['person', 'movies', 'character']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
