# Generated by Django 4.2.11 on 2025-06-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0005_alter_review_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'movies'), ('model', 'movie')), models.Q(('app_label', 'movies'), ('model', 'character')), models.Q(('app_label', 'cast'), ('model', 'person')), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
