# Generated by Django 4.2.11 on 2025-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('updated_at', models.DateTimeField(verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'persons',
            },
        ),
    ]
